### PR TITLE
thin by address

### LINKED ISSUE #5: Fat pointer equality
Since version 1.0.4, fat pointers are compared for equality using both their address and fat pointer value. For slices this is often what you want, you want to include their length in checks.

But I found a case similar to the one below where this is *not* the desired behavor.

```rust
trait A: Debug { fn test(&self) {} }
trait B: A { fn test2(&self) {}}

#[derive(Debug)]
struct Test {}
impl A for Test {}
impl B for Test {}

fn force_vtable<O: B>(v: &O) -> &dyn A {
    v
}

fn main() {
    let t = Test {};
    let tr1: &dyn A = &t;
    let tr2: &dyn A = force_vtable(&t);

    let a = ByAddress(tr1);
    let b = ByAddress(tr2);

    assert_eq!(a, b);
}
```
Here, both tr1 and tr2 are a &dyn A. They also live at the exact same address. I expected to use ByAddress to find that these two are equal.

However, force_vtable takes a generic argument that must implement B. That means that even though it returns &dyn A, the vtable *is actually different*. It contains pointers to B's functions too. That makes this assertion actually *fail*.

I hope this demonstrates that sometimes it can be useful to compare only by the address, not the whole fat pointer.

### PR DESCRIPTION
**Pull request by jdonszelmann**
See #5 
Closes #5

### CODE REVIEW

**Comment by jdonszelmann** [comment]
It looks like some more things changes because I ran cargo fmt. Hope that's okay :)

**Comment by VincentJousse** [comment]
@mbrubeck It would be very interesting to get this in a release. Do you plan to accept this ?

**Comment by jdonszelmann** [comment]
I don't think this library is very actively maintained anymore, unfortunately. But if you need it, you can use my fork using a git dependency in your rust project if you want :)

**Comment by mbrubeck** [comment]
Oops, sorry I missed this before.  This is now published as version 2.1.0.

**Comment by jdonszelmann** [comment]
Oh, very cool! Sorry, I thought you didn't update this much anymore. Good to see that you're still there

**Comment by VincentJousse** [comment]
But 2.0.0 was yanked, because of a good reason I imagine, this may be back-ported to 1.x branch, don't you think ?

**Comment by mbrubeck** [comment]
Oh, right.  Published v1.1.0.  Thanks!

**Pull request merged**
